name: rendez
description: "Plan nights out with your crew."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Supabase
  supabase_flutter: ^2.3.0

  # Navigation
  go_router: ^13.0.0

  # Maps & Location
  google_maps_flutter: ^2.5.3
  geolocator: ^11.0.0

  # State Management
  flutter_riverpod: ^2.5.0

  # UI Utilities
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0

  # Utils
  intl: ^0.19.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true